# Introduction

In [2]:
import numpy as np

In [3]:
arr1=[3,4,5,6,7]
print(type(arr1))

<class 'list'>


In [6]:
#converting list to np array
narr1=np.array(arr1)
print(type(narr1))

<class 'numpy.ndarray'>


In [9]:
#multidimensional array
arr2=[[1,2,3,4],[5,6,7,8]]
narr2=np.array(arr2)
print(narr2)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
arr3=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
narr3=np.array(arr3)
print(narr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
#dimension
print(narr3.shape)

(3, 4)


In [21]:
#2*2 array with 0
zer=np.zeros((2, 2))
print(zer)

[[0. 0.]
 [0. 0.]]


In [22]:
#2*2 array of 5

five=np.full((2,2),5)
print(five)

[[5 5]
 [5 5]]


In [23]:
#diagonal matrix
diag=np.eye(4,4)
print(diag)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Basic Numpy Operations

In [31]:
a=[1,2,11,6,8,18,12]
na=np.array(a)
print(na)
print(type(na))

[ 1  2 11  6  8 18 12]
<class 'numpy.ndarray'>


In [25]:
print(na.shape)

(7,)


In [33]:
#accessing elements
print(na[2])
print(na[1:5])
print(na[:3])
print(na[3:])
print(na[:])


11
[ 2 11  6  8]
[ 1  2 11]
[ 6  8 18 12]
[ 1  2 11  6  8 18 12]


In [28]:
#use a step of 2
print(na[1:5:2])

[2 6]


In [29]:
#using -ve index
print(a[-7:-4]) #-7 because last index won't be counted so tell an extra number, the order of being counted as the last index is reversed here

[1, 2, 11]


In [32]:
print(a[-1])

12


In [34]:
#copy an array
b=na[:]
print(b)

[ 1  2 11  6  8 18 12]


In [54]:
#concatenate two arrays 

#column wise
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])

z=np.concatenate([x,y])
print(z)

print('\n')

#row wise
a = np.array([[1,2,3,4]])  #need to have two [] for multi-dimensionality
b= np.array([[5,6,7,8]]) 
c=np.concatenate((a,b)) 
print(c)



[1 2 3 4 5 6 7 8]


[[1 2 3 4]
 [5 6 7 8]]


### Multidimensional Array Operations

In [38]:
arr=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]]
narr=np.array(arr)
print(narr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [39]:
#printing 1st row at index 0
print(narr[0])

[1 2 3 4]


In [41]:
print(narr[0,1])

2


In [42]:
#replace value at a certain index : 13 -> 22
narr[3,0]=22
print(narr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [22 14 15 16]
 [17 18 19 20]]


In [43]:
print(narr[-1]) #last row

[17 18 19 20]


In [44]:
#slicing rows and columns
print(narr[2:,:]) #all rows from index 2 onwards, all columns

[[ 9 10 11 12]
 [22 14 15 16]
 [17 18 19 20]]


# Vector Arithematic

In [55]:
x=np.array([1,2,3])
y=np.array([2,3,4])

### Addition

In [57]:
print(x+y) #vector
print('\n')
print(x+2) #scalar

[3 5 7]


[3 4 5]


### Subtraction

In [60]:
print(y-x)
print('\n')
print(y-1)

[1 1 1]


[1 2 3]


### Multiplication

In [64]:
#hadmard product
print(x*y) #element-wise multiplication

#dot product
print(np.dot(x,y))

[ 2  6 12]
20


### Division

In [65]:
print(y/x)

[2.         1.5        1.33333333]


# Matrix Arithematic

In [8]:
x=np.matrix([[1,2],[3,4]]) 
y=np.matrix([[5,3],[8,7]])

print(x)
print('\n')
print(y)
print(type(x))
#note that np.array changed to np.matrix
#it helps with matrix operations
#np matrices are stricly 2-dimensional whereas, np arrays are n-dimensional

[[1 2]
 [3 4]]


[[5 3]
 [8 7]]
<class 'numpy.matrix'>


### Addition

In [9]:
print(x+y) #matrix addition

[[ 6  5]
 [11 11]]


In [10]:
print(x+2) #element-wise

[[3 4]
 [5 6]]


### Multiplication

In [11]:
a=np.matrix([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [12]:
#haddmard multiplication
print(a*a) #benefit of using np.matrix, it did the matrix multiplication automatically for us

[[ 7 10]
 [15 22]]


In [14]:
#element-wise multiplication
print(np.multiply(a,a))

[[ 1  4]
 [ 9 16]]


# Inverse

In [15]:
from numpy.linalg import inv

In [16]:
print(inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


# Transpose

In [19]:
print(a)
print('\nTranspose: \n')
print(a.T)

[[1 2]
 [3 4]]

Transpose: 

[[1 3]
 [2 4]]
